spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_shiro_vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
logging:
  config: classpath:logback-local.xml
server:
  port: 18888
  
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_status
      logic-delete-value: 2
      logic-not-delete-value: 1